version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    environment:
      - 'DATABASE_HOST=db'
      - 'DATABASE_NAME=postgres'
      - 'DATABASE_USER=postgres'
      - 'DATABASE_PASSWORD=postgres'
    command: python3 manage.py migrate
    command: python3 manage.py runserver 0.0.0.0:8000

    #volumes:
    #  - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db